# Generated by Django 4.2.4 on 2023-10-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.JSONField(null=True),
        ),
    ]
