# Generated by Django 4.2.4 on 2023-10-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_userdata_user_subscribers_user_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.JSONField(null=True),
        ),
    ]
