# Generated by Django 4.2.4 on 2023-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='api/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
