# Generated by Django 4.2.4 on 2023-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_post_user_posts_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptions',
            field=models.JSONField(blank=True, default='[]', null=True),
        ),
    ]
