# Generated by Django 4.2.4 on 2024-01-13 10:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mediaimages_mediavideos_delete_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimages',
            name='media',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='api/media/images/'),
        ),
    ]
